---
global:
  path: files

default:
  url: http://qa.moodle.net/
  browser: chrome
  username: defaultUsername
  password: Welcome1!

qa:
  url: http://qa.moodle.net/
  browser: firefox
  username: qaUsername
  password: Welcome1!
  uri: https://www.hautelook.com/api
  auth: Authorization
  authCode: *yourAuthCode*
  contType: Content-Type
  contTypeCode: application/json
  apiUsername: *userName*
  apiPassword: *password*

stg:
  url: http://qa.moodle.net/
  browser: phantomjs
  username: stgUsername
  password: Welcome1!
