---
global:
  path: files

default:
  url: http://qa.moodle.net/
  browser: chrome
  username: defaultUsername
  password: Welcome1!

qa:
  url: https://www.hautelook.com
  url1: https://origin.staging.hautelook.com
  browser: firefox
  username: qaUsername
  password: Welcome1!
  uri: https://www.hautelook.com/api
  auth: Authorization
  authCode: HWS a5a4d56c84b8d8cd0e0a0920edb8994c
  contType: Content-Type
  contTypeCode: application/json
  apiUsername: test@user.com
  apiPassword: 12345678

stg:
  url: http://qa.moodle.net/
  browser: phantomjs
  username: stgUsername
  password: Welcome1!
