---
global:
  path: playlist-files

default:
  url: http://qa.moodle.net/
  browser: chrome
  username: defaultUsername
  password: Welcome1!

qa:
  url: http://qa.moodle.net/
  browser: firefox
  username: qaUsername
  password: Welcome1!

stg:
  url: http://qa.moodle.net/
  browser: phantomjs
  username: stgUsername
  password: Welcome1!
